#!/usr/bin/env python3
"""
scripts/seed_mcp_memory.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~
One-time seed of the MCP memory knowledge graph for the elibrary project.

Reads cluster_summaries.json and self_citations.csv and writes a JSONL
knowledge graph file that the MCP memory server reads on startup.

The graph captures:
  - Project entity (workspace, library size, venv)
  - Pipeline steps (scripts → outputs, completion status)
  - Cluster entities (labels, sizes, notes, self-citation counts)
  - Key findings (observations on a Findings entity)
  - Key file paths (entities with type "file")
  - Relations linking all of the above

After running this script, the MCP server will have the full project
context available as a queryable knowledge graph in Copilot Chat.

Usage:
    python scripts/seed_mcp_memory.py [--dry-run]

Flags:
    --dry-run   Print the JSONL lines without writing the file.

Author: Gerry Stahl
Created: March 2026
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT    = Path(__file__).resolve().parent.parent
REPORTS = ROOT / "reports"
MEMORY_DIR = ROOT / "memory"
OUT     = MEMORY_DIR / "elibrary_memory.jsonl"

NOISE_CLUSTERS   = {6, 12}
NON_CSCL_CLUSTERS = {8, 9, 15}
PENDING_CLUSTERS  = {18}

KNOWN_ORDER = [11, 1, 5, 3, 7, 4, 19, 0, 10, 6, 12, 2, 17, 13, 18, 14, 16, 9, 8, 15]


def load_cluster_summaries() -> dict:
    p = REPORTS / "cluster_summaries.json"
    if not p.exists():
        return {}
    with open(p) as f:
        return json.load(f)


def cluster_citation_counts() -> dict[int, int]:
    p = REPORTS / "self_citations.csv"
    if not p.exists():
        return {}
    counts: dict[int, int] = {}
    with open(p) as f:
        for row in csv.DictReader(f):
            cid = int(row.get("cluster_id", -1))
            counts[cid] = counts.get(cid, 0) + 1
    return counts


def build_graph() -> list[dict]:
    """Build the knowledge graph as a list of entity/relation dicts."""
    summaries  = load_cluster_summaries()
    cit_counts = cluster_citation_counts()
    records    = []

    # ── Project root entity ────────────────────────────────────────────────
    records.append({
        "type": "entity",
        "name": "elibrary_project",
        "entityType": "project",
        "observations": [
            "Workspace: /Users/GStahl2/AI/elibrary/",
            "Python venv: .venv/bin/python (never use bare python or python3)",
            "Library: 22 books, 337 chapters, 36,089 chunks",
            "Level-0 chunks (base): 17,441 — primary analysis target",
            "Embedding model: intfloat/e5-base-v2, 768-dim",
            "Anthropic Claude model for labelling: claude-haiku-4-5-20251001",
            "API key: ANTHROPIC_API_KEY set in environment, never hardcode",
            "Owner/author: Gerry Stahl — address him as Gerry in chat",
        ],
    })

    # ── Key data files ─────────────────────────────────────────────────────
    key_files = [
        ("file_faiss_index",        "file",
         ["Path: vector_store/elibrary.faiss",
          "Contents: 36,089 vectors dim=768; level-0 = 17,441 base chunks",
          "Index type: IndexFlatIP (exact cosine search)"]),
        ("file_meta_json",          "file",
         ["Path: vector_store/elibrary_meta.json",
          "Schema: {vid: {book_number, chapter_number, chunk_level, chunk_page, chunk_words, book_title, chapter_title}}"]),
        ("file_sidecar_json",       "file",
         ["Path: vector_store/chunks_bm25/sidecar.json",
          "Schema: {doc_id: {vector_id, book_number, chapter_number, chunk_text, ...}}",
          "This is the source of all chunk text for analysis"]),
        ("file_cache_pkl",          "file",
         ["Path: cache/elibrary_cache.pkl",
          "Type: ElibraryCache dataclass",
          "Access: cache.books is a LIST (not dict)",
          "Book attribute: book.book_chapters (NOT .chapters)",
          "Chapter attribute: ch.chapter_reference contains APA pub year"]),
        ("file_chunk_clusters_csv", "file",
         ["Path: reports/chunk_clusters.csv",
          "Rows: 17,441",
          "Fields: vector_id, book_number, chapter_number, book_title, chapter_title, chunk_index, chunk_page, pub_year, cluster_id, cluster_label"]),
        ("file_cluster_summaries",  "file",
         ["Path: reports/cluster_summaries.json",
          "Schema: {cluster_id: {label, summary}}",
          "Generated by: scripts/expand_cluster_summaries.py"]),
        ("file_self_citations_csv", "file",
         ["Path: reports/self_citations.csv",
          "Rows: 2,852",
          "Fields: vector_id, book_number, chapter_number, book_title, chapter_title, cluster_id, cluster_label, pub_year, cited_year, snippet"]),
        ("file_cluster_report",     "file",
         ["Path: reports/cluster_report.txt",
          "Contents: full labelled cluster listing with paragraph summaries, breadth stats, exemplars, top books"]),
        ("file_self_citation_report", "file",
         ["Path: reports/self_citation_report.txt",
          "Contents: top cited years bar chart, per-cluster summary table, per-cluster timelines"]),
        ("file_scatter_png",        "file",
         ["Path: reports/cluster_citation_scatter.png",
          "Contents: 20-panel scatter grid: x=citing year, y=cited year, bubble size proportional to frequency"]),
        ("file_heatmap_png",        "file",
         ["Path: reports/global_citation_heatmap.png",
          "Contents: full heatmap citing year x cited year with log colour scale and marginals"]),
        ("file_guide",              "file",
         ["Path: documents/GUIDE_TO_GERRY_RAG_QUERY_SYSTEM.md",
          "Contents: full project memory — RAG system architecture, analysis pipeline, script inventory, findings"]),
        ("file_project_status",     "file",
         ["Path: documents/project_status.md",
          "Contents: auto-generated compact session status — attach with #file in Copilot Chat"]),
    ]
    for name, etype, obs in key_files:
        records.append({"type": "entity", "name": name, "entityType": etype, "observations": obs})

    # ── Analysis pipeline steps ────────────────────────────────────────────
    pipeline_steps = [
        ("step_clustering", "pipeline_step", [
            "Name: Step 1 — Chunk Clustering",
            "Script: scripts/cluster_chunks.py",
            "Status: COMPLETED",
            "Method: KMeans k=20, random_state=42, n_init=10",
            "Input: 17,441 level-0 vectors from elibrary.faiss",
            "Labels: 5 exemplars per cluster sent to Claude Haiku",
            "Breadth: mean cosine distance to centroid; global mean = 0.0972",
            "Outputs: reports/chunk_clusters.csv, reports/cluster_report.txt",
        ]),
        ("step_expand_summaries", "pipeline_step", [
            "Name: Step 1b — Expanded Cluster Summaries",
            "Script: scripts/expand_cluster_summaries.py",
            "Status: COMPLETED",
            "Method: 10 exemplars per cluster, Claude Haiku, 3-5 sentence paragraphs",
            "Outputs: reports/cluster_report.txt (overwritten), reports/cluster_summaries.json",
        ]),
        ("step_citation_extraction", "pipeline_step", [
            "Name: Step 2 — Self-Citation Extraction",
            "Script: scripts/extract_self_citations.py",
            "Status: COMPLETED",
            "Result: 2,852 citation pairs from 1,085 chunks",
            "Patterns: _PAT_STAHL_FIRST, _PAT_NARRATIVE, _PAT_PAREN_BROAD",
            "Exclusion: reference list entries (Stahl, G. (YYYY)) NOT matched — G. breaks all patterns",
            "Outputs: reports/self_citations.csv, reports/self_citation_report.txt",
        ]),
        ("step_visualisation", "pipeline_step", [
            "Name: Step 3 — Visualisation",
            "Script: scripts/visualize_self_citations.py",
            "Status: COMPLETED",
            "Outputs: reports/cluster_citation_scatter.png, reports/global_citation_heatmap.png",
        ]),
        ("step_cross_cluster", "pipeline_step", [
            "Name: Step 4 — Cross-Cluster Citation Matrix",
            "Script: scripts/cross_cluster_citations.py (not yet written)",
            "Status: PENDING",
            "Goal: match cited_year back to the cluster(s) of chapters published that year",
            "Goal: produce matrix: which clusters cite work originating in which other clusters",
        ]),
    ]
    for name, etype, obs in pipeline_steps:
        records.append({"type": "entity", "name": name, "entityType": etype, "observations": obs})

    # ── Key findings ───────────────────────────────────────────────────────
    records.append({
        "type": "entity",
        "name": "key_findings",
        "entityType": "findings",
        "observations": [
            "Most-cited year: 2006 with 773 hits — corresponds to Group Cognition (MIT Press)",
            "Second most cited: 2009 with 378 hits — Studying Virtual Math Teams",
            "Third most cited: 2013 with 271 hits",
            "Most self-citations produced: Cluster 4 (VMT) with 638 pairs; 2021 alone = 219 (retrospective book)",
            "Retrospective survey: Cluster 5 citing year 2010 -> cited year 1999: 124 hits",
            "Bibliography noise: Clusters 6 and 12 — exemplars show raw reference lists not prose",
            "Early-career work: Cluster 10 (Tacit Knowledge) and Cluster 14 (HERMES) — cited years top out 1993-1995",
            "Non-CSCL: Clusters 9 (salt marsh), 8 (electronic music), 15 (sculpture) — peripheral",
            "Cluster 12 produces 150 citation pairs despite being bibliography noise — some bleed-through",
            "Cluster 17 (CSCL Foundations) top books include Book 15 in Portuguese — Brazilian CSCL chapter",
        ],
    })

    # ── Citation regex patterns ────────────────────────────────────────────
    records.append({
        "type": "entity",
        "name": "citation_regex_patterns",
        "entityType": "technical_reference",
        "observations": [
            r"_PAT_STAHL_FIRST = re.compile(r'\bStahl(?:\s+et\s+al\.?|\s+&\s+[^,()]{1,40})?,\s*(\d{4}[a-z]?)\b')",
            r"_PAT_NARRATIVE   = re.compile(r'\bStahl\s+\((\d{4}[a-z]?)\b')",
            r"_PAT_PAREN_BROAD = re.compile(r'\(([^()]*\bStahl\b[^()]*)\)')",
            "Reference list entries (Stahl, G. (YYYY). Title) are NOT matched — G. initial breaks all three patterns",
            "Verified by sampling 20 examples from sidecar.json",
        ],
    })

    # ── RAG query system ───────────────────────────────────────────────────
    records.append({
        "type": "entity",
        "name": "rag_query_system",
        "entityType": "system",
        "observations": [
            "Web app: scripts/query_app.py — Gradio at localhost:7860",
            "Terminal REPL: scripts/query_library.py",
            "Retrieval: 3-stage hybrid — dense FAISS + BM25 + Reciprocal Rank Fusion + cross-encoder reranker",
            "Reranker: BAAI/bge-reranker-base (XLM-RoBERTa, 278M params)",
            "Cloud models: claude-haiku-4-5-20251001, claude-sonnet-4-20250514, claude-opus-4-20250514",
            "Local models (Ollama): qwen2.5:14b, llama3.1:8b, gemma3:4b",
            "Conversation memory: query rewriting (Part A) + multi-turn history (Part B, last 4 turns)",
            "Persistent history: vector_store/query_history.json + query_history_embeddings.npy",
            "Status: COMPLETE and fully operational",
        ],
    })

    # ── Cluster entities ───────────────────────────────────────────────────
    for cid_str, entry in summaries.items():
        cid   = int(cid_str)
        label = entry.get("label", f"Cluster {cid}")
        summ  = entry.get("summary", "")
        cits  = cit_counts.get(cid, 0)

        notes = []
        if cid in NOISE_CLUSTERS:
            notes.append("EXCLUDE FROM CONTENT ANALYSIS: bibliography/reference-list noise")
        if cid in NON_CSCL_CLUSTERS:
            notes.append("Non-CSCL content — peripheral to main analysis")
        if cid == 18:
            notes.append("Philosophy (Marx/Heidegger) — adjacent but not CSCL proper")
        if cid == 4:
            notes.append("Most self-citations: 638 pairs; 2021 alone = 219 (retrospective book)")
        if cid == 5:
            notes.append("Retrospective survey pattern: 2010 citing year -> 1999 cited year: 124 hits")
        if cid in {10, 14}:
            notes.append("Early-career work: cited years top out at 1993-1995")

        obs = [
            f"Cluster ID: {cid}",
            f"Label: {label}",
            f"Self-citation count: {cits}",
        ]
        if summ:
            obs.append(f"Summary: {summ}")
        obs.extend(notes)

        records.append({
            "type": "entity",
            "name": f"cluster_{cid}",
            "entityType": "semantic_cluster",
            "observations": obs,
        })

    # ── Relations ──────────────────────────────────────────────────────────
    relations = [
        # Pipeline step → outputs
        ("step_clustering",         "produces",       "file_chunk_clusters_csv"),
        ("step_clustering",         "produces",       "file_cluster_report"),
        ("step_expand_summaries",   "produces",       "file_cluster_summaries"),
        ("step_expand_summaries",   "overwrites",     "file_cluster_report"),
        ("step_citation_extraction","produces",       "file_self_citations_csv"),
        ("step_citation_extraction","produces",       "file_self_citation_report"),
        ("step_visualisation",      "produces",       "file_scatter_png"),
        ("step_visualisation",      "produces",       "file_heatmap_png"),
        # Pipeline ordering
        ("step_clustering",         "precedes",       "step_expand_summaries"),
        ("step_expand_summaries",   "precedes",       "step_citation_extraction"),
        ("step_citation_extraction","precedes",       "step_visualisation"),
        ("step_visualisation",      "precedes",       "step_cross_cluster"),
        # Project → systems
        ("elibrary_project",        "contains",       "rag_query_system"),
        ("elibrary_project",        "contains",       "step_clustering"),
        ("elibrary_project",        "contains",       "key_findings"),
        # Findings → clusters
        ("key_findings",            "references",     "cluster_4"),
        ("key_findings",            "references",     "cluster_5"),
        ("key_findings",            "references",     "cluster_6"),
        ("key_findings",            "references",     "cluster_12"),
        ("key_findings",            "references",     "cluster_10"),
        ("key_findings",            "references",     "cluster_14"),
        # Key files → pipeline
        ("step_clustering",         "reads",          "file_faiss_index"),
        ("step_clustering",         "reads",          "file_meta_json"),
        ("step_clustering",         "reads",          "file_sidecar_json"),
        ("step_citation_extraction","reads",          "file_chunk_clusters_csv"),
        ("step_citation_extraction","reads",          "file_sidecar_json"),
        ("step_visualisation",      "reads",          "file_self_citations_csv"),
    ]

    for frm, rel, to in relations:
        records.append({"type": "relation", "from": frm, "to": to, "relationType": rel})

    return records


def records_to_jsonl(records: list[dict]) -> str:
    """Convert graph records to the JSONL format the MCP server expects."""
    # The MCP server stores entities and relations as separate JSONL lines.
    # Entities format: {"type": "entity", "name": ..., "entityType": ..., "observations": [...]}
    # Relations format: {"type": "relation", "from": ..., "to": ..., "relationType": ...}
    lines = []
    for r in records:
        lines.append(json.dumps(r, ensure_ascii=False))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed the MCP memory knowledge graph.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print JSONL to stdout without writing file")
    args = parser.parse_args()

    print("Building knowledge graph…")
    records = build_graph()

    entities  = sum(1 for r in records if r["type"] == "entity")
    relations = sum(1 for r in records if r["type"] == "relation")
    print(f"  {entities} entities, {relations} relations")

    jsonl = records_to_jsonl(records)

    if args.dry_run:
        print("\n── JSONL preview (first 5 records) ─────────────────")
        for line in jsonl.splitlines()[:5]:
            print(line)
        print("…")
        return

    MEMORY_DIR.mkdir(exist_ok=True)
    OUT.write_text(jsonl)
    print(f"Saved: {OUT}")
    print()
    print("Next steps:")
    print("  1. VS Code will auto-detect the MCP server via .vscode/mcp.json")
    print("     (reload the window or run 'MCP: List Servers' if needed)")
    print("  2. Trust the server when VS Code prompts")
    print("  3. In Copilot Chat, the server's tools are now available:")
    print("     search_nodes, open_nodes, read_graph,")
    print("     create_entities, add_observations, create_relations")


if __name__ == "__main__":
    main()
